blog/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^project$', views.project, name="project"),  #path('project/', views.project, name="project")
    url(r'^experience$', views.exp, name="exp"),
    url(r'^list_blog$', views.list_blog, name="list_blog"),
    url(r'^first_blog$', views.first_blog, name="first_blog"),
    url(r'^story3$', views.story3, name="story3"),
    url(r'^story1$', views.story1, name="story1"),
    path('', views.index, name="index"),
]

story_6/urls.py
from django.urls import path

from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('delete/<str:pk>', views.delete, name='activityDelete'),
    path('delete/member/<str:pk>', views.deleteMember, name='memberDelete')
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('story9/', include('story9.urls', namespace="story9")),
    path('story8/', include('story8.urls', namespace="story8")),
    path('story7/', include('story7.urls', namespace="story7")),
    path('activity/', include('story_6.urls', namespace="activity")),
    path('matkul/', include('story5.urls', namespace="matkul")),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

story_6/models.py
from django.db import models

# Create your models here.

class Activity(models.Model):
    activity = models.CharField(max_length=100)
    
    def __str__(self):
        return self.activity

class Member(models.Model):
    member = models.CharField(max_length=100)
    aktivitas = models.ForeignKey(Activity, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.member

story_6/forms.py
from django import forms
from .models import Activity, Member

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Apa yang ingin kamu lakukan ?"}),
        }

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
        widgets = {
            'member' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Masukkan namamu disini"}),
        }

story_6/views.py
from django.shortcuts import render, redirect
from .models import Member, Activity
from .forms import MemberForm, ActivityForm
from django.contrib import messages

# Create your views here.

def activity(request):
    if request.method == "POST":
        form_activ = ActivityForm(request.POST)
        form_member = MemberForm(request.POST)
        if form_activ.is_valid():
            form_activ.save()
            messages.success(request, (f"Kegiatan {request.POST['activity']} berhasil ditambahkan!"))
            return redirect('story_6:activity')
        elif form_member.is_valid():
            form_member.save()
            messages.success(request, (f"{request.POST['member']} berhasil bergabung!"))
            return redirect('story_6:activity')
        else:
            messages.warning(request, (f"Input kamu tidak sesuai!"))
            return redirect('story_6:activity')
    else:
        form_activ = ActivityForm()
        form_member = MemberForm()
        activities = Activity.objects.all()
        members = Member.objects.all()
        context = {
            'form_activ' : form_activ,
            'form_member' : form_member,
            'activities' : activities,
            'members' : members
        }
        return render(request, 'story_6/index.html', context)

def delete(request,pk):
    activity = Activity.objects.get(id=pk)
    activity.delete()
    messages.warning(request, (f"Kegiatan {activity} berhasil dihapus!"))
    print(activity)
    print(pk)
    return redirect('story_6:activity')

def deleteMember(request,pk):
    member = Member.objects.get(id=pk)
    member.delete()
    print(member)
    print(pk)
    messages.warning(request, (f"{member} berhasil dihapus!"))
    return redirect('story_6:activity')

story_6/templates/story_6/index.html
{% extends 'story5/base.html' %}

{% block page_title %}
    KEGIATAN
{% endblock page_title %}


{% block content %}
<div class="container" style="margin-top: 115px; min-height:330px;">
    <h1 class="display-3 text-center pb-4 border-bottom">Activities</h1>
    <Form method="POST" class="row my-4">
        {% csrf_token %}
        <div class="col-8 ml-auto">
            {{form_activ.activity}}
        </div>
        <button type="submit" class="btn btn-dark col-2 mr-auto" style="background-color: #e0a2ac;">Add Activity</button>
    </Form>
    <hr>

    <!--Menampilkan message-->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <!--------------------->


    <!--NGELOOP AKTIVITAS-->
    <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for activity in activities %}
        <div class="card bg-light my-4" style="width: 18rem; background-color:#724e85;">
            <div class="card-header" style="background-color: #e0a2ac;">
                <div class="row">
                    <h5 class="text-center col-10 mb-2">{{activity}}</h5>
                    <a href="{% url 'story_6:activityDelete' activity.id %}" class="col-2">
                        <button type="button" class="close mb-1">&times;</button>
                    </a>
                </div>
            </div>
            <div class="card-body" style="background-color:#9466ad;">
                <h6 class="card-title">Members</h6>
                <p></p>
                <ul>
                    <!--NGELOOP MEMBERS DI AKTIVITAS-->
                    {% for member in members %}
                        {% if member.aktivitas.id == activity.id %}
                        <li class="row">
                            <h5 class="col-10">{{member}}</h5>
                            <a href="{% url 'story_6:memberDelete' member.id %}" class="col-2">
                                <button type="button" class="close">&times;</button>
                            </a>    
                        </li>
                        {% endif %}
                    {% endfor %}
                    <!------------------------------->
                </ul>

                <!--BUTTON BUAT JOIN-->
                <form method="POST">
                    {% csrf_token %}
                    {{form_member.member}}
                    <input name="aktivitas" type="text" value="{{activity.id}}" style="display: none;"><br>
                    <button type="submit" class="btn btn-dark col-6 mt-2" style="background-color: #e0a2ac;">Join</button>
                </form>
                <!--------------------->
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}