blog/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^project$', views.project, name="project"),  #path('project/', views.project, name="project")
    url(r'^experience$', views.exp, name="exp"),
    url(r'^list_blog$', views.list_blog, name="list_blog"),
    url(r'^first_blog$', views.first_blog, name="first_blog"),
    url(r'^story3$', views.story3, name="story3"),
    url(r'^story1$', views.story1, name="story1"),
    path('', views.index, name="index"),
]

story9/urls.py
from django.urls import path
from . import views

app_name = "story9"

urlpatterns = [
    
    path('', views.profile, name ='profile'),
    path('hasilprofile/', views.hasilprofile, name = 'profile_dua'),
    path('editprofile/<int:pk>/', views.updateprofile , name = 'update_profile'),
    path('login/', views.akunlogin, name='login'),
    path('logout/', views.akunlogout, name='logout'),
    path('register/', views.akunregister, name='register')
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('story9/', include('story9.urls', namespace="story9")),
    path('story8/', include('story8.urls', namespace="story8")),
    path('story7/', include('story7.urls', namespace="story7")),
    path('activity/', include('story_6.urls', namespace="activity")),
    path('matkul/', include('story5.urls', namespace="matkul")),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

story9/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    nama    = models.CharField(max_length=50,  null=True, blank=True)
    umur    = models.IntegerField(null=True, blank=True)
    alamat  = models.CharField(max_length=200, null=True, blank=True)
    user    = models.OneToOneField(User, on_delete = models.CASCADE)

story9/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nama', 'umur', 'alamat',]

    def edit_obj(self,profile_obj):
        profile_obj.nama = self.cleaned_data['nama']
        profile_obj.umur = self.cleaned_data['umur']
        profile_obj.alamat = self.cleaned_data['alamat']
        profile_obj.save()

story9/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout

from .models import Profile
from .forms import UserForm
# Create your views here.

# Terinspirasi dari Tugas Kelompok pertama saya

def akunlogin(request):
    if not request.user.is_authenticated:
        authform = AuthenticationForm()

        if request.method == 'POST':
            authform = AuthenticationForm(data=request.POST.copy())

            if authform.is_valid():
                user = authform.get_user()
                if user != None:
                    login(request, authform.get_user())
                    return redirect('story9:profile')

        context = { 
            'active': 'login', 
            'form': authform 
            }
        return render(request, 'story9/login.html', context)
    
    else:
        return redirect('/')

def akunlogout(request):
    logout(request)
    return redirect('story9:login')

def akunregister(request):
    if not request.user.is_authenticated:
        registerform = UserCreationForm()

        if request.method == 'POST':
            registerform = UserCreationForm(request.POST)
            
            if registerform.is_valid():
                user = registerform.save()
                Profile.objects.create(user = user)
                return redirect('story9:login')
        
        context = { 
            'active': 'register', 
            'form': registerform
            }
        return render(request, 'story9/register.html', context)    
    
    else:
        return redirect('/')


#fungsi di bawah ini diedit dari Tugas Kelompok pertama saya

def profile(request): 
    return redirect('story9:profile_dua')
    

def hasilprofile(request): # ambil data user
    get_data = None
    try:
        get_data = Profile.objects.get(user = request.user)
    except:
        get_data = Profile.objects.create(user = request.user)

    context = {'data':get_data}
    return render(request, 'story9/hasil.html', context)

def updateprofile(request, pk): #update data user
    get_data = Profile.objects.get(id=pk)
    get_profile = UserForm(instance = get_data)
    
    if request.method == "POST":
        get_profile = UserForm(request.POST, instance=get_data)
        if get_profile.is_valid():
            get_profile.edit_obj(get_data)
            return redirect('story9:profile_dua')
    context = {'edit':get_profile}
    return render(request, 'story9/edit.html', context)

story9/templates/story9/edit.html
{% extends 'story5/base.html' %}
{% load static %}

{% block page_title %} 
    Edit Profile
{% endblock page_title %}

{% block content %}
 
    <div class="container" style="max-width:60%; margin-top:130px; margin-bottom:80px;">
        <h1 class="my-5">Edit Profile</h1>
    <div class="card mb-3" style="background-color: #fef0f5; box-shadow:0 0 1.0rem rgb(175, 161, 161);">
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data" class="mt-5" >
                {% csrf_token %}
                <div class="row" style="margin-left:auto; margin-right:auto; width:80%">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Nama</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ edit.nama }}
                    </div>
                </div>
            <hr>
                <div class="row" style="margin-left:auto; margin-right:auto; width:80%">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Umur</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ edit.umur }}
                    </div>
                </div>
            <hr>
                <div class="row" style="margin-left:auto; margin-right:auto; width:80%">
                    <div class="col-sm-3">
                    <h6 class="mb-0">Alamat</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ edit.alamat }}
                    </div>
                </div>
           
                    <center class="my-5">
                    <button  class="btn btn-success" type="submit">Save</button>
                    <a href="{% url 'story9:profile_dua' %}" class="btn btn-danger">Back</a>
                    </center>
                
            </form>
        </div>
    </div>

    </div>
{% endblock content %}

story9/templates/story9/hasil.html
{% extends 'story5/base.html' %}
{% load static %}

{% block page_title %}
Profile 
{% endblock page_title %}

{% block content %}
<div class="container" style="max-width:70%; margin-top:130px; margin-bottom:80px; background-color: #fef0f5;">
      <h1 class="mb-5">Profile Info</h1>
      
      <h3 class="text-center">Selamat datang {{user.username}}</h3>
      <div class="card mb-3" style="background-color: #fef0f5; box-shadow:0 0 1.0rem rgb(175, 161, 161);">
          <div class="card-body" style="margin-left:auto; margin-right:auto; width:80%">
            <div class="row">
                <div class="col-sm-4 text-secondary my-3">
                    <h6 class="mb-0">Username</h6>
                </div>
                <div class="col-sm-8 my-3">
                    {{ user.username }}
                </div>
                <hr>

                <div class="col-sm-4 text-secondary my-3">
                    <h6 class="mb-0">Nama</h6>
                </div>
                <div class="col-sm-8 my-3">
                    {{ data.nama }}
                </div>
                <hr>

                <div class="col-sm-4 text-secondary my-3">
                    <h6 class="mb-0">Umur </h6>
                </div>
                <div class="col-sm-8 my-3">
                    {{ data.umur }} tahun
                </div>
                <hr>

                <div class="col-sm-4 text-secondary my-3">
                    <h6 class="mb-0">Alamat</h6>
                </div>
                <div class="col-sm-8 my-3">
                    {{ data.alamat }}
                </div>

                <center class="my-3 px-3">
                    <a href="{% url 'story9:update_profile' data.id %}" class="btn btn-primary">Edit</a>
                </center>
            </div>
          </div>
          
      </div>
      <div class="container">
              <center>
                <a href="{% url 'story9:logout' %}" class="btn btn-danger">Logout</a>
              </center>
          </div>
      </div>
    
{% endblock content %}

story9/templates/story9/login.html
{% extends 'story5/base.html' %}
{% load static %}

{% block page_title %} 
    Log in
{% endblock page_title %}

{% block content %}
    <div class="container" style="max-width:60%; margin-top:130px; margin-bottom:80px; background-color: #fef0f5;">
    
        <h1 class="mb-5">Log in</h1>

        <!--mengunakan form.errors django -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert" style="text-align: left;">
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        {{ error }}
                    {% endfor %}
                {% endfor %}
            </div>
		{% endif %}

        <div class="card" style="background-color: #fef0f5; box-shadow:0 0 1.0rem rgb(175, 161, 161);">
            <div class="card-body">
                <form class="form-signin" method="POST" style="max-width: 80%; margin-left:auto; margin-right:auto;">  
                                  
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="inputUsername">Username</label>
                        <input type="text" id="inputUsername" name="username" class="form-control" placeholder="Username" width:70% required autofocus>
                    </div>

                    <div class="form-group">
                        <label for="inputPassword">Password</label>
                        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required> 
                    </div>
                    
                        <button class="btn btn-lg btn-outline-primary btn-block" type="submit">Log in</button>
                    
                </form>
                </div>
            </div>
          
        <p class="text-center">Register akun <a href="{% url 'story9:register' %}"> disini</a></p>
        </div>
{% endblock content %}

story9/templates/story9/profile.html
{% load static %}

{% block page_title %} Profile {% endblock page_title %}

{% block content %}
    <br>
    <div class = "title">
      <h1> Profile </h1>
    </div>

    <div class="container">
      <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              <p> Silahkan memasukkan data diri anda terlebih dahulu</p>
              <p>Nama : {{ profile.nama }}</p>
              <p>Umur : {{ profile.umur }}</p>
              <p>Domisili : {{ profile.alamat }}</p>
          </fieldset>
          <div class="form-group" >
             
              <button href ="{% url 'story9:profile_dua' %}"class="btn btn-outline-info" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>

    <div class="form-group" >     
      <button href ="{% url 'story9:profile_dua' %}"class="btn btn-outline-info" type="submit">cek</button>
    </div>
{% endblock content %}

story9/templates/story9/register.html
{% extends 'story5/base.html' %}
{% load static %}

{% block page_title %} 
    Register
{% endblock page_title %}

{% block content %}
    <div class="container" style="max-width:60%; margin-top:130px; margin-bottom:80px; background-color: #fef0f5;">

        <h1 class="mb-5">Register</h1>

         <!--mengunakan form.errors django -->
        {% if form.errors %}
		<div class="alert alert-danger" role="alert" style="text-align: left;">
			There are some errors:
			<ul class="mb-0">
				{% for field, errors in form.errors.items %}
					{% for error in errors %}
						<li>{{ error }}</li>
					{% endfor %}
				{% endfor %}
			</ul>
		</div>
		{% endif %}

        <div class="card" style="background-color: #fef0f5; box-shadow:0 0 1.0rem rgb(175, 161, 161);">
            <div class="card-body">
                <form class="form-signin" method="POST" style="max-width: 80%; margin-left:auto; margin-right:auto;">
                    
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputUsername">Username</label>
                    <input type="text" id="inputUsername" name="username" class="form-control" placeholder="Username" required autofocus>
                </div>
                <div class="form-group">
                    <label for="inputPassword">Password</label>
                    <input type="password" id="inputPassword" name="password1" class="form-control" placeholder="Password" required>
                </div>
                <div class="form-group">
                    <label for="inputPasswordConfirm">Password Confimation</label>
                    <input type="password" id="inputPasswordConfirm" name="password2" class="form-control" placeholder="Password" required> 
                </div>
                <button class="btn btn-lg btn-outline-primary btn-block" type="submit">Register</button>
            </form>
            </div>
        </div>
    </div>
            
        
{% endblock content %}