blog/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^project$', views.project, name="project"),  #path('project/', views.project, name="project")
    url(r'^experience$', views.exp, name="exp"),
    url(r'^list_blog$', views.list_blog, name="list_blog"),
    url(r'^first_blog$', views.first_blog, name="first_blog"),
    url(r'^story3$', views.story3, name="story3"),
    url(r'^story1$', views.story1, name="story1"),
    path('', views.index, name="index"),
]

story5/urls.py
from django.urls import path 
from django.conf.urls import url

from . import views 

app_name = 'story5'

urlpatterns = [
    url(r'^detail/(?P<detail_id>[0-9]+)$', views.detail, name='detail'),
    url(r'^update/(?P<update_id>[0-9]+)$', views.update, name='update'),
    url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
    path('list/', views.list, name='list'),
    path('create/', views.create, name='create'),

]

story7/urls.py
from django.urls import path 
from django.conf.urls import url

from . import views 

app_name = 'story7'

urlpatterns = [
    path('', views.accordion, name="accordion"),
]

story9/urls.py
from django.urls import path
from . import views

app_name = "story9"

urlpatterns = [
    
    path('', views.profile, name ='profile'),
    path('hasilprofile/', views.hasilprofile, name = 'profile_dua'),
    path('editprofile/<int:pk>/', views.updateprofile , name = 'update_profile'),
    path('login/', views.akunlogin, name='login'),
    path('logout/', views.akunlogout, name='logout'),
    path('register/', views.akunregister, name='register')
]

story_6/urls.py
from django.urls import path

from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('delete/<str:pk>', views.delete, name='activityDelete'),
    path('delete/member/<str:pk>', views.deleteMember, name='memberDelete')
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('story9/', include('story9.urls', namespace="story9")),
    path('story8/', include('story8.urls', namespace="story8")),
    path('story7/', include('story7.urls', namespace="story7")),
    path('activity/', include('story_6.urls', namespace="activity")),
    path('matkul/', include('story5.urls', namespace="matkul")),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'blog/index.html')

def story1(request):
    return render(request, 'blog/story1.html')

def story3(request):
    return render(request, 'blog/story3.html')

def first_blog(request):
    return render(request, 'blog/first_blog.html')

def list_blog(request):
    return render(request, 'blog/list_blog.html')

def exp(request):
    return render(request, 'blog/exp.html')

def project(request):
    return render(request, 'blog/project.html')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <head>
        <title>
            {% block page_title %}

            {% endblock page_title %}
        </title>
        <link rel="shortcut icon" href="{% static 'blog/img/kuda.png' %}">

        <!-----CSS BOOTSTRAP----->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="../../static/blog/css/index.css">
    </head>

    <body class="home mt-5">
        {% include 'blog/navbar.html' %}
        {% block content %}

        {% endblock content %}
        {% include 'blog/footer.html' %}
    </body>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>

blog/templates/blog/exp.html
{% extends 'blog/base.html' %}
{% load static %}

<html>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block page_title %}
        EXPERIENCE
    {% endblock page_title %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">

    {% block content %}
    <!--EXPERIENCE-->
  <section class="experience" id="experience">
    <div class="container">
      <div class="row mt-5">
        <div class="col">
          <h3><b>EXPERIENCE</b></h3>
        </div>
      </div>

      <div class="row mt-5">
        <div class="col-md my-2">
              <div class="card">
                <a href="#" class="card-img-top"><img src="{% static 'blog/img/iac.jpg' %}" class="card-img-top" alt="..." / ></a>
                <div class="card-body">
                  <h4 href="#" class="link-exp">IACILE Vol.3</h4>
                  <p class="card-text">Pengalaman yang tak terlupakan saat mengerjakan ProKer ini yaitu saat kami para panitia
                    berjualan stiker ke pengunjung Car Free Day
                  </p>
                </div>
            </div>
        </div>

          <div class="col-md my-2">
                <div class="card">
                  <a href="#" class="card-img-top"><img src="{% static 'blog/img/olim.jpg' %}" class="card-img-top" alt="..." / height=></a>
                  <div class="card-body">
                    <h4 href="#" class="link-exp">OLIM UI 2019</h4>
                    <p class="card-text">Menjadi bagian staff divisi Renang Olim UI 2019 memberikan pelajaran yang banyak bagi saya, 
                      mulai dari kedisiplinan, kebersamaan, sampai keceriaan
                    </p>
                  </div>
              </div>
          </div>

          <div class="col-md my-2">
            <div class="card">
              <a href="#" class="card-img-top"><img src="{% static 'blog/img/olim.jpg' %}" class="card-img-top" alt="..." / height=></a>
              <div class="card-body">
                <h4 href="#" class="link-exp">OLIM UI 2019</h4>
                <p class="card-text">Menjadi bagian staff divisi Renang Olim UI 2019 memberikan pelajaran yang banyak bagi saya, 
                  mulai dari kedisiplinan, kebersamaan, sampai keceriaan
                </p>
              </div>
          </div>
      </div> 
      </div>
  </section>
  <!----------->
    {% endblock content %}

blog/templates/blog/first_blog.html
{% extends 'blog/base.html' %}
{% load static %}

<html>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block page_title %}
        MY BAD HABITS
    {% endblock page_title %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
      <h1 class="display-2">My Bad Habits</h1>
      <p class="lead">Disaat hal-hal aneh menjadi kebiasaanmu </p>
    </div>
  </div>

  <!--cerita-->
  <div class="container text-justify" style="margin-top: 70px; margin-bottom:70px;">
    <p><b>Halo kamuu, hope you have a good day yaa.</b></p>

    <p>Yes aight, kebiasaan-kebiasaan buruk yang gue punya. Sebenarnya ga terlalu banyak sih, but still .... bad (hehe). Nah, kalau dari judulnya, kamu pasti udah bisa  nebak apa aja yang akan gue ceritain di sesi blog ini.</p>
    <p>Oke, kita mulai dari yang paling mainstream yaa. Mungkin kebiasaan buruk ini juga banyak dimiliki orang lain,
        ya apalagi kalau bukan <b>nunda-nunda makan</b>. Sebenernyaa, gue adalah typical orang yang ga jaim sama makanan,
        selagi itu enak, gue bakal makan, apalagi kalo gratis yekann (double pleasure wk).
        Tapi yang jadi masalah adalahh gue pengen diet (wkwk), entah kenapa di usia yang makin tua ((astaghfirullah, jadi inget dosa)),
        gue sangat mengidamkan tubuh yang ideal, banyak yang bilang kalo tubuh gue udah ideal jika diukur dengan BMS, tapi ya tetep aja
        gue masih kurang puas, <i>actually I have a disease that requires me to maintain my weight to stay at normal.</i>
        Nah, kalian bisa menilai sendiri kan kalo dari tujuan yang gue punya itu sebenarnya oke-oke aja, tapi yang salah ya cara gue (hehe),
        <i>No matter how good your goals are, if you use the wrong way to achieve it, it still be wrong</i>. Gue sering
        banget makan sehari cuma sekali, yang seharusnya tiga kali, jadi gue gabung aja buat sekali makan di siang. Sarapan yang jadi momen penting 
        itu jarang banget gue lakuin, yaa ini <i>totally wrong</i> sih. Kalian tau kan ada pepatah yang bilang "<i>eat breakfast like a king,
        lunch like prince, dinner like a pauper"</i>". Mungkin udah banyak yang tau arti dari istilah itu, 
        tapi gue mau ulang sedikit disini, kenapa eat breakfast like a king? Karena pada saat sarapan kita harus makan 
        yang banyak, apa aja makan deh, sarapan merupakan makanan pertama yang kita konsumsi setelah beristirahat di malam hari. Hal tersebut perlu 
        dilakukan karena kita harus mengisi glukosa dalam diri yang merupakan hal penting bagi otak dan sumber energi kita sepanjang hari. 
        Jika kita melewatkan sarapan, gula dalam diri kita akan rendah dan akan menurunkan produktivitas diri dalam beraktivitas sepanjang hari.
        Nah selebihnya kalian tau lah apa artinya, yang jelas intinya jangan lewatin sarapan dan jangan gabung-gabungin waktu makan,
        makan di waktu yang tepat itu penting banget. Kalau kalian mau diet, 
        <a href="https://hellosehat.com/hidup-sehat/nutrisi/berat-badan-ideal/panduan-diet-sehat/#gref" style="color:black; text-decoration:underline;">diet-lah dengan cara yang benar</a>
        , jangan kayak orang kekurangan makanan.
    <figure>
        <img src="{% static 'blog/img/eat.PNG' %}" style="display: block; margin:auto;" width=50% height=70%>
        <figcaption style="text-align:center;"><i>Makan di waktu yang tepat itu pentingg</i></figcaption>
    </figure>
    </p>
   
    <p>Oke next,<b> gue suka muntahin makanan kalau gue lagi kesal, marah, atau sedih gitu</b>. Gue kurang tau seberapa aneh kebiasaan ini, 
        tapi yang jelas gue tau kalau kebiasaan ini berbahaya buat pencernaan. Menurut <a href="https://hellosehat.com/hidup-sehat/nutrisi/9-efek-jangka-panjang-pada-penderita-bulimia/">artikel</a>
        yang gue baca, banyak efek samping dari kebiasaan ini. Tapi entah kenapa, setelah gue muntahin makanan dalam kondisi yang udah gue sebutin diatas, 
        gue merasa lebih tenang, emosi gue berkurang, dan bisa ketawa lagi wkwk. Berhubung gue tipe orang yang suka mendem masalah, cara yang paling cepet buat ngeluapinnya ya dengan cara ini. Mungkin
        agak bingung ya maksudnya apa wkwk. Jadi kadang di rumah atau diluar, suka ada aja yang bikin mood jelek, nah cara paling praktis buat ilangin mood jelek ini ya dengan cara memuntahkan makanan 
         <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-frown" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path fill-rule="evenodd" d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683z"/>
            <path d="M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
          </svg>. Jangan ditiru yaa <br><br>
        <figure>
            <img src="{% static 'blog/img/fine.jpg' %}" style="display:block; margin:auto;" width=50% height=70%>
            <figcaption style="text-align:center;"><i>Depressed</i></figcaption>
        </figure>
    </p>

    <p>And, the last is <b>gue suka gigitin sisi-sisi lidah gue pake geraham tanpa sadar</b>. Nah, gue gatau kapan kebiasaan ini muncul tepatnya. Tapi 
        kalo ga salah, gue dulu itu suka banget makan permen karet, nah kalo ga ada permen karet atau yang bisa gue kunyah, gue gigitin lidah.
        Oiya, parahnya gue tuh sampe ketiduran gitu gigitinnya, jadi pas bangun, lidah gue tuh sampe ada bekas gigitannya, bahkan 
        pernah sampe berdarah gitu. Kayaknya untuk kebiasaan ini efek sampingnya ga ada ya. Eh ada deh, kalo keseringan gigitin lidah bisa bikin
        lidah kamu berdarah gaes, hehe
        <figure>
            <img src="{% static 'blog/img/lidah.jpg' %}" style="display:block; margin:auto;" width=50% height=70%>
            <figcaption style="text-align:center;"><i>Gigitin lidah sakit</i></figcaption>
        </figure>
    </p>

    <p>Oke kayaknya segitu aja cerita tentang kebiasaan-kebiasaan buruk gue. Sebenarnya masih ada lagi, tapi gue rasa 
        cukup dulu untuk sekarang. Thanks for reading all <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-smile-upside-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 1a7 7 0 1 1 0 14A7 7 0 0 1 8 1zm0-1a8 8 0 1 1 0 16A8 8 0 0 1 8 0z"/>
            <path fill-rule="evenodd" d="M4.285 6.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 4.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 3.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683z"/>
            <path d="M7 9.5C7 8.672 6.552 8 6 8s-1 .672-1 1.5.448 1.5 1 1.5 1-.672 1-1.5zm4 0c0-.828-.448-1.5-1-1.5s-1 .672-1 1.5.448 1.5 1 1.5 1-.672 1-1.5z"/>
          </svg> See ya later.
    </p>
    </div>
{% endblock content %}

blog/templates/blog/list_blog.html
{% extends 'blog/base.html' %}
{% load static %}
<html>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block page_title %}
        BLOG
    {% endblock page_title %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/index.css' %}">

    
{% block content %}
<section class="blogs" id="blogs">
    <div class="container">
    <div class=" row">
        <div class="col-lg-8 mb-4">
            <div class="card mb-4">
                <h5 class="card-header list-group-item-primary">Blog</h5>
                    <div class="card-body">
                    <h5 class="card-title">My Bad Habits</h5>
                    <p class="card-text">Oke, kita mulai dari yang paling mainstream yaa. Mungkin kebiasaan buruk ini juga banyak dimiliki orang lain,</p>
                    <a href="{% url 'blog:first_blog' %}" class="btn btn-primary">More</a>
                    </div>
            </div>

            <div class="card mb-4">
                <h5 class="card-header list-group-item-warning list-group-item-primary">Hobi</h5>
                    <div class="card-body">
                    <h5 class="card-title">Why I love Swim</h5>
                    <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vitae asperiores et, est omnis, nobis ratione aliquam cum corporis</p>
                    <a href="#" class="btn btn-primary">More</a>
                    </div>
            </div>

            <div class="card">
                <h5 class="card-header list-group-item-success">Pengetahuan</h5>
                    <div class="card-body">
                    <h5 class="card-title">7 Manfaat Minum Air Putih Setelah Bangun Tidur</h5>
                    <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vitae asperiores et, est omnis, nobis ratione aliquam cum corporis</p>
                    <a href="#" class="btn btn-primary">More</a>
                    </div>
            </div>
        </div>

        <div class="col-lg 4">
            <div class="list-group">
                <h3 class="list-group-item list-group-item-dark"><b>Kategori</b></h3>
                <a href="#" class="list-group-item list-group-item-action list-group-item-primary">Blog</a>
                <a href="#" class="list-group-item list-group-item-action list-group-item-success">Pengetahuan</a>
                <a href="#" class="list-group-item list-group-item-action list-group-item-danger">Meme</a>
                <a href="#" class="list-group-item list-group-item-action list-group-item-warning">Hobi</a>
              </div>
        </div>
    </div>
</div>
</div>
</section>
{% endblock content %}
</html>

blog/templates/blog/navbar.html
<link rel="stylesheet" href="../../static/blog/css/index.css">

 <!--NAVBAR-->
 <div class="main">
  <nav class="navbar fixed-top navbar-expand-lg">
    <div class="container-fluid">
    <a href="{% url 'blog:index' %}" class="navbar-brand"><img src="../../static/blog/img/horse.ico" / width="30%"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link page-scroll" href="{% url 'blog:story1' %}">STORY 1</a>
        </li>
        <li class="nav-item page-scroll">
          <a class="nav-link" href="#contact">CONTACT</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:list_blog' %}">BLOG</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story5:list' %}">MATA KULIAH</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story_6:activity' %}">KEGIATAN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story7:accordion' %}">ACCORDION</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story8:index' %}">BUKU</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story9:login' %}">LOGIN</a>
        </li>
      </ul>
    </div>
  </nav>
</div>
</div>

blog/templates/blog/story1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">

    {% block page_title %}
      <title>More Profile</title>
    {% endblock page_title %}
      <link rel="shortcut icon" href="{% static 'blog/img/kuda.png' %}">

  </head>

  <body class="body">
    {% block content %}
    <div class="container mb-5">
      <div class="row">
        <div class="col-sm-2">
          <a href="{% url 'blog:index' %}" class="back"><img src="../../static/blog/img/back.svg" / width="30px"></a>
        </div>
        <div class="col-sm-8">
          <h1><b>MY PROFILE</b></h1>
        </div>
      </div>
      
      <div class="row mb-2" style="justify-content: center; display:flex; align-content:center">
        <div class="col-lg-4">
          <div class="card mb-3">
            <div class="card">
              <div class="card" style="background-color: antiquewhite;">
                <h4 style="text-align: center;"><b>MY DETAILS</b></h4>
              </div>
              <img src="{% static 'blog/img/15.jpg' %}" class="card-img-top img-thumbnail" width="30%" height="200px" style="background-color: antiquewhite;" alt="foto"> <!--rounded-circle-->
                        <div class="card-body" style="display:grid; grid-template-columns: auto 1fr; background-color: antiquewhite; font-family:'Lucida'; row-gap: .2rem; column-gap: .6rem; ">
                          <div class="kiri">Nama</div>
                          <div class="kanan"><b>Puspita Sari Matovanni</b></div>
                          <div class="kiri">NPM</div>
                          <div class="kanan"><b>1906299080</b></div>
                          <div class="kiri">Jurusan</div>
                          <div class="kanan"><b>Sistem Informasi</b></div>
                          <div class="kiri">Universitas</div>
                          <div class="kanan"><b>Universitas Indonesia</b></div>
                          <div class="kiri">Hobi</div>
                          <div class="kanan"><b>Tidur</b></div>
                        </div>
                        <div class="card" style="background-color: #724e85">
                          <div><h5 style="color:#724e85">gchhvhjv</h5></div>
                        </div>
            </div>
            </div>
          </div>


          <div class="col-lg-6">
            <div class="card" style="background-color: antiquewhite;">
              <div class="card" style="background-color: #724e85";>
                <h4 style="text-align: center; color:white;"><b>ABOUT ME</b></h4>
            </div>
            <div class="card-body"  style="background-color: antiquewhite; font-family:'Lucida';">
              <p style="background-color: antiquewhite; font-family:'Lucida';">Halo, aku mahasiswa Sistem Informasi Fakultas Ilmu Komputer Universitas Indonesia angkatan 2019. 
                Sistem Informasi sangat erat kaitannya dengan teknologi.
                Pada era ini,  teknologi hampir tidak dapat dipisahkan dari kehidupan manusia, hampir semua hal menggunakan teknologi dengan tujuan 
                untuk memudahkan aktivitas kita. Maka dari itu, menurutku sangat penting mempelajari teknologi, selain untuk mempermudah hidup kita,
                mempelajari teknologi juga dapat melatih aktivitas kita menjadi lebih terstruktur. <br>
                Saat ini aku sedang mengambil mata kuliah Perancangan dan Pemrograman Web (PPW), dan halaman ini merupakan tugas pertamaku di mata kuliah PPW. 
                Dalam mata kuliah ini, aku berharap dapat semakin memperluas pengetahuanku di bidang  teknologi khususnya Web Developing.<br></p>
                <h5 style="text-align: center;"><b>EDUCATION</b></h5>
                  <!--TABEL RIWAYAT PENDIDIKAN-->
                  <table class="table table-striped" style="background-color: antiquewhite;">
                    <tbody style="text-align: center;">
                      <tr>
                        <td>2016 - 2019</td>
                        <td><b>SMAN 54 Jakarta</b></td>
                      </tr>
                      <tr>
                        <td>2013 - 2016</td>
                        <td><b>SMPN 3 Jakarta</b></td>
                      </tr>
                      <tr>
                        <td>2007 - 2013</td>
                        <td><b>SDN Kebon Manggis 03</b></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
            </div>
          </div>
        </div>
      </div>

        </div>
      </div>
    </div>
   
    <!--CONTACT-->
<div class="contact-logo  pt-3" id="contact-logo">
  <a href="https://t.me/kudapunny">
    <img class="icon-contact" src="{% static 'blog/img/4.png' %}" width="60px" alt="telegram">
</a>
<a href="https://gitlab.com/puspita_vanni">
    <img class="icon-contact" src="{% static 'blog/img/gitlab.png' %}" width="60px" alt="gitlab">
</a>
<a href="https://www.instagram.com/puspitavanni_/">
    <img class="icon-contact" src="{% static 'blog/img/ig.png' %}" width="60px" alt="ig">
</a>
<a href="mailto:puspita.sari92@ui.ac.id">
  <img class="icon-contact" src="{% static 'blog/img/email.ico' %}" width="90px" alt="email">
</a>
</div>
    {% endblock content %}
  </body>
</html>